class Formats:
    date = "%Y-%m-%d"
    short_date = "%m-%d"
    time = "%H:%M:%S"
    complete_time = "%H:%M:%S.%f"
    short_time = "%H:%M"
    datetime = "%Y-%m-%d %H:%M:%S"
    complete_datetime = "%Y-%m-%dT%H:%M:%S"
    time_12hr = "%I:%M %p"
    timestamp = "%s.%f"
    dmy_slashes = "%d/%m/%Y"
    dmy_dashes = "%d-%m-%Y"
    datetime_with_am_pm = "%Y-%m-%d %I:%M-%p"
    mdy_slashes = "%m/%d/%Y"
    day_name = "%A"