# Generated by Django 5.2.3 on 2025-07-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_grand_total_order_updated_at_and_more'),
        ('users', '0002_remove_user_auth_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_id', 'status'], name='order_customer_status_idx'),
        ),
    ]
